### ISSUE TITLE
關於開源更新 & ESLint的格式修復

### ISSUE THREAD

**Issue by WinsonOTP** [WinsonOTP/RadishBot#17]
接下來將會進行開源的更新，但想詢問以下問題：

@nk980113 
- 關於ESLint的格式修復，由於目前使用之編譯平台無該功能，且電腦中的VSCode已卡頓致無法運行。若要更新開源，不知如何進行ESLint格式調整。

**Comment by ItzMiracleOwO** [comment]
Github Action 🤔

**Comment by nk980113** [comment]
![image](https://user-images.githubusercontent.com/50331539/142848528-215ffbf0-6e4f-48d5-aa13-4f598b9a03ed.jpeg)
題外話：有人知道我貢獻的圖案要用叉子嗎

**Comment by ItzMiracleOwO** [comment]
🤔 用 GitHub Action 他會自動開PR欸

**Comment by nk980113** [comment]
然後還要去merge PR
倒不如直接先用CLI改好

**Comment by ItzMiracleOwO** [comment]
🤔  鬼知道你們各自用各自的config, 到頭來亂七八糟 而且merge PR 就一個鍵阿 🤔

**Comment by nk980113** [comment]
![image](https://user-images.githubusercontent.com/50331539/143014365-588e6042-5b7f-4337-be2c-d5a00e64ab84.jpeg)
