### ISSUE TITLE
Some problems about the project

### ISSUE THREAD

**Issue by ItzMiracleOwO** [WinsonOTP/RadishBot#5]
1. The bot does not support messageCreate commands
2. Slash commands wont work
3. config.json is unsecure, .env will be better

I hope we will add these feature later!
Have a nice day!

**Comment by kyometori** [comment]
雖然我不是開發者，但我講一下我的看法
- 我認為訊息指令不太必要，因為這隻機器人理論上是申請不到 intent 的，造出來明年就不能用了。除非他不想驗證。
- 斜線指令應該是可以動的吧，我們用的很好
- 我不認為 config.json 比 .env 不安全，推上遠端檔案庫都會出事。如果你說 ignore 就好了，那 config 也可以這樣做。

**Comment by ItzMiracleOwO** [comment]
剛clone下來的，照樣報錯
![image](https://user-images.githubusercontent.com/76854136/141700729-f56853ea-10f9-4878-b9d7-a3b70de8ec24.png)
![image](https://user-images.githubusercontent.com/76854136/141700735-962e90d0-d056-4f72-befe-f5f252537830.png)
![image](https://user-images.githubusercontent.com/76854136/141700762-461af9b8-dc38-49e0-8de4-edfb3b752613.png)

**Comment by ItzMiracleOwO** [comment]
關於.env的問題，請看 https://stackoverflow.com/questions/51937363/env-vs-config-json/51937555

**Comment by ItzMiracleOwO** [comment]
剛剛翻了一下源代碼，斜綫指令的問題應該是因爲指令沒有注冊成功

**Comment by kyometori** [comment]
你給的那篇說了 這些都只應該在開發階段用#

斜線指令我就不清楚了，因為在已經有的地方他是可以動的，也許我們要問問 @WinsonOTP

**Comment by ItzMiracleOwO** [comment]
那個斜線指令呼叫 ./sub_command.js 之後就好了🤔 應該是註冊了斜線指令

**Comment by kyometori** [comment]
那個 PR 已經合併了，問題應該被解決了。我想這個 issue 可以關閉了 @WinsonOTP
